config/routes.rb
Rails.application.routes.draw do
  resources :sentences
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "splash", to: "splash#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sentence.rb
class Sentence < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  before_action :set_sentence, only: %i[ show edit update destroy ]

  # GET /sentences or /sentences.json
  def index
    @sentences = Sentence.all
    @sentence = Sentence.new
  end

  # GET /sentences/1 or /sentences/1.json
  def show
  end

  # GET /sentences/new
  def new
    @sentence = Sentence.new
  end

  # GET /sentences/1/edit
  def edit
  end

  # POST /sentences or /sentences.json
  def create
    @sentence = Sentence.new(sentence_params)

    respond_to do |format|
      if @sentence.save
        format.json { render :show, status: :created, location: @sentence }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sentences/1 or /sentences/1.json
  def update
    respond_to do |format|
      if @sentence.update(sentence_params)
        format.html { redirect_to sentence_url(@sentence), notice: "Sentence was successfully updated." }
        format.json { render :show, status: :ok, location: @sentence }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sentences/1 or /sentences/1.json
  def destroy
    @sentence.destroy

    respond_to do |format|
      format.html { redirect_to sentences_url, notice: "Sentence was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sentence
      @sentence = Sentence.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sentence_params
      params.require(:sentence).permit(:value)
    end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WordSplashApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sentences/_form.html.erb
<%= form_with(model: sentence) do |form| %>
  <% if sentence.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sentence.errors.count, "error") %> prohibited this sentence from being saved:</h2>

      <ul>
        <% sentence.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :value, style: "display: block" %>
    <%= form.text_field :value %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sentences/_input.html.erb
<%= stylesheet_link_tag 'input.css' %>
<%= form_with(model: sentence) do |form| %>
  <div class="input">
    <span>
      <%= form.text_field :value, class: 'text-field' %>
    </span>
    <span>
      <%= form.submit 'Create', class: 'submit' %>
    </span>
  </div>
<% end %>

app/views/sentences/_sentence.html.erb
<div id="<%= dom_id sentence %>">
  <p>
    <%= sentence.value %>
  </p>

</div>

app/views/sentences/edit.html.erb
<h1>Editing sentence</h1>

<%= render "form", sentence: @sentence %>

<br>

<div>
  <%= link_to "Show this sentence", @sentence %> |
  <%= link_to "Back to sentences", sentences_path %>
</div>

app/views/sentences/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sentences</h1>

<div id="sentences">
  <% @sentences.each do |sentence| %>
    <%= render sentence %>
    <p>
      <%= link_to "Show this sentence", sentence %>
    </p>
  <% end %>
</div>

<div id="input">
  <%= render "input", sentence: @sentence %>
</div>

<%= link_to "New sentence", new_sentence_path %>

app/views/sentences/new.html.erb
<h1>New sentence</h1>

<%= render "form", sentence: @sentence %>

<br>

<div>
  <%= link_to "Back to sentences", sentences_path %>
</div>

app/views/sentences/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sentence %>

<div>
  <%= link_to "Edit this sentence", edit_sentence_path(@sentence) %> |
  <%= link_to "Back to sentences", sentences_path %>

  <%= button_to "Destroy this sentence", @sentence, method: :delete %>
</div>

app/views/splash/index.html.erb
<h1>New sentence</h1>